### ISSUE TITLE
Breaks on Meteor 1.0.4

### ISSUE THREAD

**Issue by icenpop** [Jabbslad/basic-auth#5]
Basic Auth crashed upon upgrading to Meteor@1.0.4 from 1.0.3.2. Looks like `WebApp.__basicAuth__` is undefined.

```
(STDERR) TypeError: Object #<Object> has no method '__basicAuth__'
(STDERR)     at [object Object].HttpBasicAuth.protect (packages/jabbslad:basic-auth/basic-auth.js:19:1)
(STDERR)     at app/server/auth/http_basic_auth.js:2:11
(STDERR)     at app/server/auth/http_basic_auth.js:4:3
(STDERR)     at /Users/jacquesblom/Repo/clients/oupcms/.meteor/local/build/programs/server/boot.js:222:10
(STDERR)     at Array.forEach (native)
(STDERR)     at Function._.each._.forEach (/Users/jacquesblom/.meteor/packages/meteor-tool/.1.0.43.fosvsm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
(STDERR)     at /Users/jacquesblom/Repo/clients/oupcms/.meteor/local/build/programs/server/boot.js:117:5
```

**Comment by mccormjt** [comment]
also having this problem
