### ISSUE TITLE
Package crashes meteor app

### ISSUE THREAD

**Issue by martip-vccp** [Jabbslad/basic-auth#6]
I installed the package like `meteor add jabbslad:basic-auth` and then add to my server code this:

```
Meteor.startup(function () {
        //Auth
        var basicAuth = new HttpBasicAuth("admin", "password");
        basicAuth.protect(['/admin']);
});

```

But as soon as I run the app, I get this errors:

```
W20150408-12:17:25.327(1)? (STDERR) TypeError: Cannot read property 'connect' of undefined
W20150408-12:17:25.328(1)? (STDERR)     at [object Object].HttpBasicAuth.protect (packages/jabbslad:basic-auth/basic-auth.js:10:1)
W20150408-12:17:25.328(1)? (STDERR)     at app/presentation-quiz.js:237:19
W20150408-12:17:25.328(1)? (STDERR)     at /Users/martip/Sites/presentation-quiz/.meteor/local/build/programs/server/boot.js:212:5
=> Exited with code: 7
```

**Comment by martip-vccp** [comment]
I solved it by installing the previous version:

```meteor add jabbslad:basic-auth@=0.2.1```

Because I haven't updated to the new meteor version.

Cheers!
